// Project Agent — provider-independent architecture.
//
// The Agent is project-scoped: it belongs to whichever project is currently
// active in the DevWorkspace Zustand store. Its conversation history is
// persisted per-project (in IndexedDB, alongside the project's other data)
// so context survives switching projects, switching tabs (Workspace ↔
// Visual Editor Studio ↔ Code Converter), and refreshing the browser.
//
// Provider independence:
// - We define a `ModelProvider` interface. Anyone can implement one
//   (OpenAI, Anthropic, z-ai-web-dev-sdk, a local LLM, etc.) and plug it in.
// - When no provider is configured, the agent UI honestly says so — it
//   never fabricates AI responses.
//
// Tool-based:
// - The agent has access to a curated set of project-aware tools
//   (read file, list files, scan, get framework, get preview status, etc.).
// - Tools are NOT given uncontrolled access to other LUCIAN systems
//   (no auth, no profile, no Settings access).
//
// Persisted conversations live in a separate IndexedDB store
// `agent_conversations` keyed by projectId so they don't bloat the
// `projects` store (which is loaded in full on app start).

import type { Project, ProjectFile } from "@/types/workspace";

/** A single message in an agent conversation. */
export interface AgentMessage {
  id: string;
  role: "user" | "assistant" | "tool";
  /** Free-text content for user/assistant messages; tool result for `tool`. */
  content: string;
  /** When this message was sent/received. */
  timestamp: number;
  /** For assistant messages that called a tool: which tool, with what args. */
  toolCall?: {
    name: string;
    args: Record<string, unknown>;
  };
  /** For tool messages: which tool produced this result. */
  toolName?: string;
  /** True when this message was generated by an actual model (not a placeholder). */
  fromModel: boolean;
}

/** A conversation = ordered list of messages for a given project. */
export interface AgentConversation {
  projectId: string;
  messages: AgentMessage[];
  updatedAt: number;
}

/** Input passed to a tool's execute function. */
export interface ToolContext {
  /** The currently active project (or null if none). */
  project: Project | null;
  /** All files of the active project (lazy-loaded by the caller). */
  files: ProjectFile[];
  /** Read a file's content from IndexedDB by path. */
  readFile: (path: string) => Promise<string | undefined>;
  /** Write a file's content (persists to IndexedDB + hot-syncs to runtime). */
  writeFile: (path: string, content: string) => Promise<void>;
  /** Re-scan the project for env vars / services. */
  scanProject: () => Promise<void>;
  /** Get the current preview/runtime status (e.g. 'running' / 'error'). */
  getRuntimeStatus: () => Promise<{ status: string; serverUrl: string | null; error: string | null }>;
  /** Get the latest terminal output (if a runtime is running). */
  getTerminalOutput: () => Promise<string>;
}

/** A tool the agent can call. */
export interface AgentTool {
  /** Stable identifier (used in toolCall.name). */
  name: string;
  /** Human-readable description shown to the model. */
  description: string;
  /** JSON-schema-ish parameter description, for the model. */
  parameters: {
    type: "object";
    properties: Record<string, { type: string; description: string }>;
    required?: string[];
  };
  /** Execute the tool with the given args + context. Returns a string result. */
  execute: (args: Record<string, unknown>, ctx: ToolContext) => Promise<string>;
}

/** A model provider adapter. Plug any LLM provider in here. */
export interface ModelProvider {
  /** Stable identifier — e.g. "openai", "anthropic", "z-ai", "noop". */
  id: string;
  /** Human-readable label for the UI. */
  label: string;
  /** True when the provider is actually configured and able to call out. */
  configured: boolean;
  /**
   * Submit the conversation + available tools. Returns the assistant's
   * response (which may include a tool call that the runner will dispatch).
   */
  submit: (params: {
    messages: AgentMessage[];
    tools: AgentTool[];
    systemPrompt: string;
  }) => Promise<{
    content: string;
    toolCall?: { name: string; args: Record<string, unknown> };
  }>;
}

/**
 * NoOp provider — used when no real model is configured.
 *
 * The agent UI surfaces this honestly so the user knows they need to
 * connect a real provider before the agent can do anything.
 */
export const noopProvider: ModelProvider = {
  id: "noop",
  label: "No model configured",
  configured: false,
  async submit() {
    return {
      content:
        "No model is configured. Connect a model provider (OpenAI, Anthropic, a local LLM, etc.) in the Agent panel settings to enable AI responses. Until then, I can only use tools on request via the explicit tool buttons.",
    };
  },
};

/** In-memory holder for the currently registered provider. */
let currentProvider: ModelProvider = noopProvider;

/** Register a model provider. Future submissions will use it. */
export function setModelProvider(provider: ModelProvider): void {
  currentProvider = provider;
}

/** Get the currently registered provider. */
export function getModelProvider(): ModelProvider {
  return currentProvider;
}

/**
 * Run one agent turn:
 *   1. Submit conversation + tools to the provider.
 *   2. If the model returns a toolCall, dispatch it and add the tool result.
 *   3. Re-submit with the new tool result so the model can produce a final
 *      assistant message.
 *
 * Stops after a max of 4 tool round-trips to prevent infinite loops.
 *
 * Returns the messages to append (assistant + tool results + final assistant).
 */
export async function runAgentTurn(
  userMessage: string,
  ctx: ToolContext,
  tools: AgentTool[],
  history: AgentMessage[],
  systemPrompt: string,
): Promise<AgentMessage[]> {
  const provider = getModelProvider();
  const out: AgentMessage[] = [];

  const userMsg: AgentMessage = {
    id: `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    role: "user",
    content: userMessage,
    timestamp: Date.now(),
    fromModel: false,
  };
  const fullHistory = [...history, userMsg];

  // Submit up to 5 times to allow tool round-trips.
  for (let i = 0; i < 5; i++) {
    const response = await provider.submit({
      messages: [...fullHistory, ...out],
      tools,
      systemPrompt,
    });

    if (response.toolCall) {
      // Add the assistant message that called the tool.
      out.push({
        id: `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
        role: "assistant",
        content: response.content,
        timestamp: Date.now(),
        toolCall: response.toolCall,
        fromModel: provider.configured,
      });

      // Dispatch the tool.
      const tool = tools.find((t) => t.name === response.toolCall!.name);
      let toolResult: string;
      if (!tool) {
        toolResult = `Error: tool "${response.toolCall.name}" does not exist.`;
      } else {
        try {
          toolResult = await tool.execute(response.toolCall.args, ctx);
        } catch (err) {
          toolResult = `Error executing tool: ${err instanceof Error ? err.message : String(err)}`;
        }
      }
      out.push({
        id: `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
        role: "tool",
        content: toolResult,
        timestamp: Date.now(),
        toolName: response.toolCall.name,
        fromModel: false,
      });
      continue;
    }

    // Final assistant message — no tool call.
    out.push({
      id: `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      role: "assistant",
      content: response.content,
      timestamp: Date.now(),
      fromModel: provider.configured,
    });
    break;
  }

  return out;
}
